USE [master]
GO

/****** Object:  Database [FlightReservation]    Script Date: 23/08/2018 15:13:21 ******/
CREATE DATABASE [FlightReservation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FlightReservation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\FlightReservation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FlightReservation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\FlightReservation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [FlightReservation] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FlightReservation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FlightReservation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FlightReservation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FlightReservation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FlightReservation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FlightReservation] SET ARITHABORT OFF 
GO

ALTER DATABASE [FlightReservation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FlightReservation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FlightReservation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FlightReservation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FlightReservation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FlightReservation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FlightReservation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FlightReservation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FlightReservation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FlightReservation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FlightReservation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FlightReservation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FlightReservation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FlightReservation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FlightReservation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FlightReservation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FlightReservation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FlightReservation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FlightReservation] SET  MULTI_USER 
GO

ALTER DATABASE [FlightReservation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FlightReservation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FlightReservation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FlightReservation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FlightReservation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FlightReservation] SET QUERY_STORE = OFF
GO

USE [FlightReservation]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [FlightReservation] SET  READ_WRITE 
GO


