//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservartion.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public string Flight_id { get; set; }
        public string Departure { get; set; }
        public string Destination { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<decimal> FuelConsumption { get; set; }
        public Nullable<decimal> Number_of_Adult { get; set; }
        public Nullable<decimal> Number_of_Children { get; set; }
        public Nullable<decimal> Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
